# -*- coding: utf-8 -*-
"""Netflix_catalog_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zVUTC36Q-uvdYsL5EdFAh0giwoSCXuH2
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("netflix_titles.csv")
print(df.head())
print(df.shape)
print(df.info())
print(df.isnull().sum())
print(df.duplicated().sum())

"""#**Data Wrangling**

##Hadling missing values
"""

df["director"] = df["director"].fillna("Unknown")
df["cast"] = df["cast"].fillna("Unknown")
df["country"] = df["country"].fillna("Unknown")

df.dropna(subset=["date_added", "rating", "duration"], inplace=True)

print(df.isnull().sum())

"""##Converting Data Types"""

df["date_added"] = pd.to_datetime(df["date_added"].str.strip())
print(df["date_added"].dtype)
print(df["date_added"].head())

"""##Splitting Duration Column"""

df["duration_minutes"] = df[df["type"] == "Movie"]["duration"].str.replace(" min", "").astype(float)
df["duration_seasons"] = df[df["type"] == "TV Show"]["duration"].str.replace(" Seasons", "").str.replace(" Season", "").astype(float)

print(df[["type", "duration", "duration_minutes", "duration_seasons"]].head(10))

"""#**Business Questions**

##Has Netflix been growing its catalog over the years or is growth slowing down?
"""

content_per_year = df.groupby(df["date_added"].dt.year)["title"].count()
print(content_per_year)

"""##Finding:
Netflix added very little content between 2008 and 2015, with fewer than 100 titles per year. Starting in 2016, the platform experienced rapid catalog growth, peaking at 2,016 titles added in 2019. Growth slowed in 2020 and 2021, though 2021 data may be incomplete as the dataset does not cover the full year.
"""

ax= content_per_year.plot(kind = "line",
                     title = "Content added to Netflix Per Year",
                     xlabel = "Year",
                     ylabel = "Number of Titles",
                     color = "darkred",
                     marker = "o",
                     figsize = (10,5))

plt.tight_layout()
plt.show()

"""##Business Insight:
Netflix's rapid catalog expansion between 2016 and 2019 suggests a period of heavy investment in content acquisition. The slowdown in 2020 and 2021 may reflect a strategic shift toward quality over quantity, or the impact of the COVID-19 pandemic on production. Netflix should monitor whether this trend continues, as a declining catalog growth rate could affect subscriber retention.

##How has the balance between Movies and TV Shows shifted over the years?
"""

content_type = df.groupby([df["date_added"].dt.year, "type"]) ["title"].count().unstack()
print(content_type)

"""##Finding:
In the early years, the catalog consisted almost exclusively of Movies. After 2016, Netflix began investing more in TV Shows, peaking between 2019 and 2020. However, even with growth from near zero to almost 600 titles, the increase in Movies was significantly larger, maintaining their dominance in the catalog.
"""

content_type.plot(kind = "bar",
                  title = "Movies vs Tv shows Added Per Year",
                  xlabel = "Year",
                  ylabel = "Number of Titles",
                  color = ["red", "darkred"],
                  figsize = (12,5))

plt.tight_layout()
plt.show()

"""##Business insight:
While Movies continue to dominate Netflix's catalog, the steady growth of TV Shows since 2016 suggests a strategic shift toward serialized content. Netflix should evaluate whether this trend aligns with audience consumption patterns, as the data alone does not indicate which format drives higher engagement or subscriber retention.

##Which countries are the largest content producers and where should Netflix expand local production?
"""

content_by_country = df[df["country"] != "Unknown"]["country"].value_counts().head(10)
print(content_by_country)

"""##Finding:
The United States is by far the largest content producer with 2,809 titles, followed by India (972) and the United Kingdom (418). The remaining countries produce significantly less content, with numbers dropping sharply after the top three.
"""

ax = content_by_country.plot(kind = "barh",
                        title = "Top 10 Content Producing Countries",
                        xlabel = "Number of Titles",
                        ylabel = "Country",
                        color = "darkred",
                        figsize = (10,6))
for i, v in enumerate(content_by_country):
  ax.text(v+4, i, f"{v}", ha="left", fontweight = "bold")


plt.tight_layout()
plt.show()

"""##Business Insight:
The dominance of the United States suggests a heavy reliance on a single market. Countries like Japan, South Korea, and Spain show emerging production presence and could represent opportunities for local content investment to attract regional audiences and diversify the catalog.

#What audience is Netflix primarily targeting based on content ratings?
"""

ratings = df["rating"].value_counts()
print(ratings)

"""#Finding:
The majority of Netflix's catalog is rated TV-MA (mature audiences) with 3,205 titles, followed by TV-14 with 2,157 titles. Together they represent over 60% of the catalog, indicating that Netflix primarily targets adult audiences.
"""

ax = ratings.plot(kind = "barh",
                         title = "Netflix Target Based in Content Rating",
                         xlabel = "Rating",
                         ylabel = "Audience",
                         color = "darkred",
                         figsize = (10,6))

for i, v in enumerate(ratings):
  ax.text(v+5, i, f"{v}", ha="left", fontweight="bold")

plt.tight_layout()
plt.show()

"""##Business Insight:
Netflix's catalog is heavily skewed toward mature and older teen audiences. While this reflects a clear strategic focus on adult content, it also reveals an underserved opportunity in family and children's programming, categories like TV-G, TV-Y, and TV-Y7 represent a small fraction of the catalog and could be expanded to attract a broader subscriber base.

#Which genres have the highest representation and which are underserved in the catalog?
"""

genres = df["listed_in"].str.split(", ").explode().value_counts().head(15)
print(genres)

"""##Finding:
International Movies and Dramas are the most represented genres in Netflix's catalog, with 2,752 and 2,426 titles respectively. It is worth noting that "International Movies" is a broad label that groups content from multiple non-American countries, which may inflate its numbers. Among clearly defined genres, Comedies (1,674) and Action & Adventure (859) are the strongest performers, while Kids' TV (448) and Docuseries (394) are the least represented in the top 15.
"""

ax = genres.plot(kind = "barh",
            title = "Top 15 Most Common Genres on Netflix",
            xlabel = "Number of Titles",
            ylabel = "Genres in Catalog",
            color = "darkred",
            figsize = (10,6))

for i, v in enumerate(genres):
  ax.text(v+5, i, f"{v}", ha="left", fontweight="bold")

plt.xlim(0,3000)
plt.tight_layout()
plt.show()

"""##Business Insight:
Netflix's catalog is heavily concentrated in International Movies and Dramas, suggesting a strong focus on broad, globally appealing content. Kids' TV and Docuseries are significantly underrepresented, indicating potential growth opportunities in family entertainment and documentary content — categories that could attract new subscriber segments and diversify the platform's appeal.

#Conclusions
The analysis of Netflix's catalog reveals several strategic patterns. Content additions grew rapidly between 2016 and 2019, peaking at over 2,000 titles, but have slowed since then, suggesting a potential shift toward quality over quantity. Movies continue to dominate the catalog over TV Shows, though serialized content has grown steadily since 2016. The United States is by far the largest content producer, while countries like Japan, South Korea, and Spain represent emerging opportunities for local production investment. In terms of audience targeting, Netflix primarily serves mature and older teen audiences, with family and children's content remaining underserved. Finally, International Movies and Dramas lead the catalog by genre, while Kids' TV and Docuseries present untapped growth opportunities to attract broader subscriber segments.
"""